# -*- coding: utf-8 -*-
"""Session8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehlQCKEqhXGWRYkg09YlwWn_ndM1L257
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 1, 100)

def sin_function(x):
    return np.sin(x)

def cos_function(x):
    return np.cos(x)

y_sin = sin_function(x)
y_cos = cos_function(x)

fig, axes = plt.subplots(1, 2)

# Left panel: sin(x)
axes[0].plot(x, y_sin)
axes[0].set_title("sin(x)")

# Right panel: cos(x)
axes[1].plot(x, y_cos)
axes[1].set_title("cos(x)")

plt.tight_layout()
plt.savefig("sin_cos_plot.pdf")
plt.show()
