# -*- coding: utf-8 -*-
"""Session10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPZYE0GMCXUCr7txEW_EERLy563eZwDS
"""

import numpy as np
import matplotlib.pyplot as plt

shape = 2.0
scale = 2.0
n = 1000

random_numbers = np.random.gamma(shape, scale, n)

plt.figure()

plt.hist(random_numbers, bins=100)

plt.xlabel("Value")
plt.ylabel("Frequency")
plt.title("Histogram of 1000 Gamma-Distributed Random Numbers")

plt.savefig("gamma_histogram.pdf")

plt.show()