# -*- coding: utf-8 -*-
"""Session9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ur3aPZHOAL2dlPpuoUBSfdR7EfayB0bF
"""

import numpy as np
import matplotlib.pyplot as plt

random_numbers = np.random.uniform(0, 1, 1000)

plt.figure()

plt.hist(random_numbers, bins=100)

plt.xlabel("Random Number Value")
plt.ylabel("Frequency")

plt.title("Histogram of Uniform Random Numbers")

plt.savefig("uniform_histogram.pdf")
plt.show()
